repos:
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
    -   id: tests
        name: tests
        entry: uv run pytest tests/unit
        language: system
        types: [python]
        pass_filenames: false
    -   id: ruff
        name: ruff
        entry: uv run ruff
        language: system
        types: [python]
        pass_filenames: false
        args: ['check', '--fix', 'src', 'tests']
    -   id: ruff-format
        name: ruff-format
        entry: uv run ruff
        language: system
        types: [python]
        pass_filenames: false
        args: ['format', 'src', 'tests']
